version: "3"
services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/var/www/app
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: dev